### ISSUE TITLE
Frontend roadmap

### ISSUE THREAD

**Issue by robindemourat** [medialab/trajectories-of-engagement#3]
- [X] update dependencies
- [X] setup basic routing
- [X] setup password protection
- [X] intro route structure
- [ ] stories summary route structure
  - [x] modal
  - [x] story item
  - [ ] search and sort bar
- [X] single response route structure
- [X] texts loading mechanism
- [ ] form components
  - [ ] simple string
  - [ ] select
  - [ ] list of strings (crud)
  - [ ] boolean
